emc4j:
  loader:
    defaultLoadType: LastSuccessfull #default
  platform:
    rootPath: ./data
  maven:
    directory: ${emc4j.platform.rootPath}/.m2/repository
  registry:
#    snapshotsAllowed: true
    defaults:
      core:
        groupId: com.treilhes.emc4j
        artifactId: emc4j.core.registry
        mandatory: true
      mandatory:
        groupId: com.treilhes.emc4j
        artifactId: emc4j.app.registry.mandatory
        mandatory: true
      optionals:
        groupId: com.treilhes.emc4j
        artifactId: emc4j.app.registry.optional

#dynamic port
server:
  port: 0
  address: 127.0.0.1
  tomcat:
    basedir: ${emc4j.platform.rootPath}
    threads:
      max: 5
      min-spare: 2
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
#      buffered: false
      suffix: .log
      file-date-format: yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b'

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        id:
          db_structure_naming_strategy: com.treilhes.emc4j.boot.jpa.naming.ModuleAwareImplicitDatabaseObjectNamingStrategyImpl
    hibernate:
      naming:
        physical-strategy: com.treilhes.emc4j.boot.jpa.naming.ModuleAwarePhysicalNamingStrategyStandardImpl
        implicit-strategy: com.treilhes.emc4j.boot.jpa.naming.ModuleAwareImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
#    open-in-view: false
  datasource:
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:emc4j;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:${emc4j.platform.rootPath}/emc4j-h2-db
    username: sa
    password: ""

